site_name: 'udemy-python-app-2'
repo_url: https://github.com/TMcManemy/udemy-python-app-2
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'
